openapi: 3.0.1
info:
  title: Adoptame API - Pets
  description: API documentation for managing pets in Adoptame
  version: 1.0.0
paths:
  /api/pets:
    get:
      summary: Get all pets
      tags:
        - Pets
      responses:
        '200':
          description: List of all pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '500':
          description: Internal server error
    post:
      summary: Create a new pet
      tags:
        - Pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetInput'
      responses:
        '200':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Incomplete values
        '500':
          description: Internal server error
  /api/pets/{pid}:
    put:
      summary: Update a pet by ID
      tags:
        - Pets
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: The ID of the pet to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetUpdate'
      responses:
        '200':
          description: Pet updated successfully
        '404':
          description: Pet not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a pet by ID
      tags:
        - Pets
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: The ID of the pet to delete
      responses:
        '200':
          description: Pet deleted successfully
        '404':
          description: Pet not found
        '500':
          description: Internal server error
  /api/pets/with-image:
    post:
      summary: Create a new pet with an image
      tags:
        - Pets
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the pet
                specie:
                  type: string
                  description: Specie of the pet
                birthDate:
                  type: string
                  format: date
                  description: Birth date of the pet
                image:
                  type: string
                  format: binary
                  description: Image file of the pet
      responses:
        '200':
          description: Pet with image created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Incomplete values
        '500':
          description: Internal server error
components:
  schemas:
    Pet:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier for the pet
        name:
          type: string
          description: Name of the pet
        specie:
          type: string
          description: Specie of the pet
        birthDate:
          type: string
          format: date
          description: Birth date of the pet
        image:
          type: string
          description: Image URL of the pet
        adopted:
          type: boolean
          description: Whether the pet has been adopted
    PetInput:
      type: object
      properties:
        name:
          type: string
          description: Name of the pet
        specie:
          type: string
          description: Specie of the pet
        birthDate:
          type: string
          format: date
          description: Birth date of the pet
    PetUpdate:
      type: object
      properties:
        name:
          type: string
          description: Name of the pet
        specie:
          type: string
          description: Specie of the pet
        birthDate:
          type: string
          format: date
          description: Birth date of the pet
        adopted:
          type: boolean
          description: Whether the pet has been adopted
